#!/usr/bin/env bash

if [ -z "${EQENV_NODE_VERSION}" ]; then
  abort "The environment doesn't specify the version of 'node'."
fi

EQENV_NODE_DIR="${EQENV_STORAGE}/node"
EQENV_NODE_HOME="${EQENV_NODE_DIR}/${EQENV_NODE_VERSION}"
EQENV_NODE_BIN="${EQENV_NODE_HOME}/bin"
EQENV_EXECUTABLE="${EQENV_NODE_BIN}/corepack"

if [ -s "${EQENV_EXECUTABLE}" ]; then
  exec $EQENV_EXECUTABLE $@
else
  echo "Could not find the installation of 'node@${EQENV_NODE_VERSION}'."
fi
