#!/usr/bin/env bash

source "${EQENV_HELPERS}/env"

EQENV_NODE_VERSION=$(get_tool_version node)
EQENV_NPM_VERSION=$(get_tool_version npm)

if [[ -z "${EQENV_NPM_VERSION}" ]] && [[ -z "${EQENV_NODE_VERSION}" ]]; then
  abort "The environment doesn't specify the version of 'node' or 'npm'."
fi

EQENV_NODE_DIR="${EQENV_STORAGE}/node"
EQENV_NODE_HOME="${EQENV_NODE_DIR}/${EQENV_NODE_VERSION}"
EQENV_NODE_BIN="${EQENV_NODE_HOME}/bin"

EXECUTABLE_FROM_NODE="${EQENV_NODE_HOME}/lib/node_modules/npm/bin/npx-cli.js"

EQENV_NPM_DIR="${EQENV_STORAGE}/npm"
EQENV_NPM_HOME="${EQENV_NPM_DIR}/${EQENV_NPM_VERSION}"
EQENV_NPM_BIN="${EQENV_NPM_HOME}/bin"

EXECUTABLE_FROM_NPM="${EQENV_NPM_BIN}/npx-cli.js"

EQENV_EXECUTABLE_VERSION="'node' or 'npm'"

if [ -z "${EQENV_NPM_VERSION}" ]; then
  EQENV_EXECUTABLE_VERSION="npm@${EQENV_NPM_VERSION}"
  EQENV_EXECUTABLE="${EXECUTABLE_FROM_NPM}"
elif [ -z "${EQENV_NODE_VERSION}" ]; then
  EQENV_EXECUTABLE_VERSION="node@${EQENV_NODE_VERSION}"
  EQENV_EXECUTABLE="${EXECUTABLE_FROM_NODE}"
fi

if [ -s "${EQENV_EXECUTABLE}" ]; then
  exec $EQENV_EXECUTABLE $@
else
  echo "Could not find the installation of ${EQENV_EXECUTABLE_VERSION}."
fi
