#!/usr/bin/env sh

EQ_NODE_DIR="${EQ_TOOLS}/node"
EQ_NODE_VERSION=$(get_tool_version node)
EQ_NODE_HOME="${EQ_NODE_DIR}/${EQ_NODE_VERSION}"
EQ_NODE_BIN="${EQ_NODE_HOME}/bin"
EQ_NODE_EXECUTABLE="${EQ_NODE_BIN}/node"
EQ_NPM_EXECUTABLE="${EQ_NODE_HOME}/lib/node_modules/npm/bin/npm-cli.js"
EQ_NPX_EXECUTABLE="${EQ_NODE_HOME}/lib/node_modules/npm/bin/npx-cli.js"

get_arch() {
  local arch
  arch="$(uname -m | tr '[:upper:]' '[:lower:]')"

  case "${arch}" in
    x86_64 | amd64) arch="x64" ;;
    armv*) arch="arm" ;;
    arm64 | aarch64) arch="arm64" ;;
  esac

  # `uname -m` in some cases mis-reports 32-bit OS as 64-bit, so double check
  if [ "${arch}" = "x64" ] && [ "$(getconf LONG_BIT)" -eq 32 ]; then
    arch=i686
  elif [ "${arch}" = "arm64" ] && [ "$(getconf LONG_BIT)" -eq 32 ]; then
    arch=arm
  fi

  case "$arch" in
    x64*) ;;
    arm64*) ;;
    *) return 1
  esac

  printf '%s' "${arch}"
}

get_os() {
  local result="$(uname -s | tr '[:upper:]' '[:lower:]')"

  printf '%s' "${result}"
}

set_node() {
  local EQ_ROOT=$(dirname ${BASH_SOURCE[0]})

  ln -Fs "${EQ_ROOT}/node-run" "${EQ_SHIMS}/node"
  chmod +x "${EQ_SHIMS}/node"

  ln -Fs "${EQ_ROOT}/npm-run" "${EQ_SHIMS}/npm"
  chmod +x "${EQ_SHIMS}/npm"

  ln -Fs "${EQ_ROOT}/npx-run" "${EQ_SHIMS}/npx"
  chmod +x "${EQ_SHIMS}/npx"

  echo "Using node@${EQ_NODE_VERSION}"
}

install_node() {
  mkdir -p "${EQ_NODE_HOME}"

  local os=$(get_os)
  local arch=$(get_arch)
  local archive_url="https://nodejs.org/download/release/v${EQ_NODE_VERSION}/"
  local archive="node-v${EQ_NODE_VERSION}-${os}-${arch}"
  local archive_ext=".tar.gz"

  archive_url="${archive_url}${archive}${archive_ext}"

  if [ ! -f "${EQ_NODE_EXECUTABLE}" ]; then
    echo "Downloading node@${EQ_NODE_VERSION}"

    download "${archive_url}" > "${EQ_NODE_HOME}/${archive}${archive_ext}"
    tar -xf "${EQ_NODE_HOME}/${archive}${archive_ext}" -C "${EQ_NODE_HOME}"
    cp -r "${EQ_NODE_HOME}/${archive}/" "${EQ_NODE_HOME}"
    chmod +x "${EQ_NODE_EXECUTABLE}"

    rm -rf "${EQ_NODE_HOME}/${archive}"
    rm "${EQ_NODE_HOME}/${archive}${archive_ext}"
  fi

  set_node
}

if [ ! "$EQ_NODE_VERSION" = "" ]; then
  echo "\n=> node"
  install_node
fi
