#!/usr/bin/env sh

EQ_PNPM_DIR="${EQ_TOOLS}/pnpm"
EQ_PNPM_VERSION=$(get_tool_version pnpm)
EQ_PNPM_HOME="${EQ_PNPM_DIR}/${EQ_PNPM_VERSION}"
EQ_PNPM_BIN="${EQ_PNPM_HOME}/bin"
EQ_PNPM_EXECUTABLE="${EQ_PNPM_BIN}/pnpm.cjs"
EQ_PNPX_EXECUTABLE="${EQ_PNPM_BIN}/pnpx.cjs"

set_pnpm() {
  local EQ_ROOT=$(dirname ${BASH_SOURCE[0]})

  ln -Fs "${EQ_ROOT}/pnpm-run" "${EQ_SHIMS}/pnpm"
  chmod +x "${EQ_SHIMS}/pnpm"

  ln -Fs "${EQ_ROOT}/pnpx-run" "${EQ_SHIMS}/pnpx"
  chmod +x "${EQ_SHIMS}/pnpx"

  echo "Using pnpm@${EQ_PNPM_VERSION}"
}

install_pnpm() {
  mkdir -p "${EQ_PNPM_HOME}"

  local archive_url="https://registry.npmjs.org/pnpm/-/"
  local archive="pnpm-${EQ_PNPM_VERSION}"
  local archive_ext=".tgz"

  archive_url="${archive_url}${archive}${archive_ext}"

  if [ ! -f "${EQ_PNPM_EXECUTABLE}" ]; then
    echo "Downloading pnpm@${EQ_PNPM_VERSION}"

    download "${archive_url}" > "${EQ_PNPM_HOME}/${archive}${archive_ext}"
    tar -xf "${EQ_PNPM_HOME}/${archive}${archive_ext}" -C "${EQ_PNPM_HOME}"
    cp -r "${EQ_PNPM_HOME}/package/" "${EQ_PNPM_HOME}"
    chmod +x "${EQ_PNPM_EXECUTABLE}"
    chmod +x "${EQ_PNPX_EXECUTABLE}"

    rm -rf "${EQ_PNPM_HOME}/package"
    rm "${EQ_PNPM_HOME}/${archive}${archive_ext}"
  fi

  set_pnpm
}

if [ ! "$EQ_PNPM_VERSION" = "" ]; then
  echo "\n=> pnpm"
  install_pnpm
fi
