#!/usr/bin/env sh

EQ_APOLLO_ROVER_DIR="${EQ_TOOLS}/apollo-rover"
EQ_APOLLO_ROVER_VERSION=$(get_tool_version apollo-rover)
EQ_APOLLO_ROVER_HOME="${EQ_APOLLO_ROVER_DIR}/${EQ_APOLLO_ROVER_VERSION}"
EQ_APOLLO_ROVER_BIN="${EQ_APOLLO_ROVER_HOME}"
EQ_APOLLO_ROVER_EXECUTABLE="${EQ_APOLLO_ROVER_BIN}/run.js"

set_apollo_rover() {
  local EQ_ROOT=$(dirname ${BASH_SOURCE[0]})

  ln -Fs "${EQ_ROOT}/run" "${EQ_SHIMS}/rover"
  chmod +x "${EQ_SHIMS}/rover"

  echo "Using apollo-rover@${EQ_APOLLO_ROVER_VERSION}"
}

install_apollo_rover() {
  mkdir -p "${EQ_APOLLO_ROVER_HOME}"

  local archive_url="https://registry.npmjs.org/@apollo/rover/-/"
  local archive="rover-${EQ_APOLLO_ROVER_VERSION}"
  local archive_ext=".tgz"

  archive_url="${archive_url}${archive}${archive_ext}"

  if [ ! -f "${EQ_APOLLO_ROVER_EXECUTABLE}" ]; then
    echo "Downloading apollo-rover@${EQ_APOLLO_ROVER_VERSION}"

    download "${archive_url}" > "${EQ_APOLLO_ROVER_HOME}/${archive}${archive_ext}"
    tar -xf "${EQ_APOLLO_ROVER_HOME}/${archive}${archive_ext}" -C "${EQ_APOLLO_ROVER_HOME}"
    cp -r "${EQ_APOLLO_ROVER_HOME}/package/" "${EQ_APOLLO_ROVER_HOME}"
    chmod +x "${EQ_APOLLO_ROVER_EXECUTABLE}"

    local ppwd=$(pwd)
    cd $EQ_APOLLO_ROVER_HOME
    npm i --no-audit --silent --no-progress
    cd $ppwd

    rm -rf "${EQ_APOLLO_ROVER_HOME}/package"
    rm "${EQ_APOLLO_ROVER_HOME}/${archive}${archive_ext}"
  fi

  set_apollo_rover
}

if [ ! "${EQ_APOLLO_ROVER_VERSION}" = "" ]; then
  echo "\n=> apollo-rover"
  install_apollo_rover
fi
