#!/usr/bin/env bash

source "${EQENV_HELPERS}/env"

EQENV_GO_VERSION=$(get_tool_version go)

if [ -z "${EQENV_GO_VERSION}" ]; then
  abort "The environment doesn't specify the version of 'go'."
fi

EQENV_GO_DIR="${EQENV_STORAGE}/go"
EQENV_GO_HOME="${EQENV_GO_DIR}/${EQENV_GO_VERSION}"
EQENV_GO_BIN="${EQENV_GO_HOME}/bin"

EQENV_EXECUTABLE="${EQENV_GO_BIN}/go"

if [ -s "${EQENV_EXECUTABLE}" ]; then
  export GOROOT="${EQENV_GO_HOME}"
  exec $EQENV_EXECUTABLE $@
else
  echo "Could not find the installation of 'go@${EQENV_GO_VERSION}'."
fi
